service: mutants

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  mutant:
    handler: bin/mutant
    events:
      - http:
          path: mutant
          method: post
